package io.hashnut.sdk.models;


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;

public class CoinInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.CoinCode
     *
     * @mbggenerated
     */
    /**
     * 币种代号,例如:usdt，bnb等
     *
     * @mbggenerated
     */
    private String coinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.ChainCode
     *
     * @mbggenerated
     */
    /**
     * 币种所在的链
     *
     * @mbggenerated
     */
    private String chainCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.ContractAddr
     *
     * @mbggenerated
     */
    /**
     * 币种智能合约地址(可选)
     *
     * @mbggenerated
     */
    private String contractAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.CoinDesc
     *
     * @mbggenerated
     */
    /**
     * 币种描述(可选)
     *
     * @mbggenerated
     */
    private String coinDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.CreateTime
     *
     * @mbggenerated
     */
    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.UpdateTime
     *
     * @mbggenerated
     */
    /**
     * 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.IsToken
     *
     * @mbggenerated
     */
    /**
     * 是否是 token，1.是 0.否
     *
     * @mbggenerated
     */
    private Boolean isToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.Enable
     *
     * @mbggenerated
     */
    /**
     * 是否开通，1.是 0.否
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.ChainEnable
     *
     * @mbggenerated
     */
    /**
     * 是否支持链上通道 0.不支持 1.支持
     *
     * @mbggenerated
     */
    private Boolean chainEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.L2Enable
     *
     * @mbggenerated
     */
    /**
     * 是否支持L2通道 0.不支持 1.支持
     *
     * @mbggenerated
     */
    private Boolean l2Enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.GateWayEnable
     *
     * @mbggenerated
     */
    /**
     * 是否支持网关通道 0.不支持 1.支持
     *
     * @mbggenerated
     */
    private Boolean gateWayEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.Decimals
     *
     * @mbggenerated
     */
    /**
     * 代币的精度，例如：usdt为小数点后6位
     *
     * @mbggenerated
     */
    private Integer decimals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.MaxWithDrawAmount
     *
     * @mbggenerated
     */
    /**
     * 最大提现额度10wu
     *
     * @mbggenerated
     */
    private byte[] maxWithDrawAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.MinWithDrawAmount
     *
     * @mbggenerated
     */
    /**
     * 最小提现额度100u
     *
     * @mbggenerated
     */
    private byte[] minWithDrawAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coin_info.MinObtainAmount
     *
     * @mbggenerated
     */
    /**
     * 最小到账额度10u
     *
     * @mbggenerated
     */
    private byte[] minObtainAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_coin_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.CoinCode
     *
     * @return the value of t_coin_info.CoinCode
     *
     * @mbggenerated
     */
    public String getCoinCode() {
        return coinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.CoinCode
     *
     * @param coinCode the value for t_coin_info.CoinCode
     *
     * @mbggenerated
     */
    public void setCoinCode(String coinCode) {
        this.coinCode = coinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.ChainCode
     *
     * @return the value of t_coin_info.ChainCode
     *
     * @mbggenerated
     */
    public String getChainCode() {
        return chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.ChainCode
     *
     * @param chainCode the value for t_coin_info.ChainCode
     *
     * @mbggenerated
     */
    public void setChainCode(String chainCode) {
        this.chainCode = chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.ContractAddr
     *
     * @return the value of t_coin_info.ContractAddr
     *
     * @mbggenerated
     */
    public String getContractAddr() {
        return contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.ContractAddr
     *
     * @param contractAddr the value for t_coin_info.ContractAddr
     *
     * @mbggenerated
     */
    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.CoinDesc
     *
     * @return the value of t_coin_info.CoinDesc
     *
     * @mbggenerated
     */
    public String getCoinDesc() {
        return coinDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.CoinDesc
     *
     * @param coinDesc the value for t_coin_info.CoinDesc
     *
     * @mbggenerated
     */
    public void setCoinDesc(String coinDesc) {
        this.coinDesc = coinDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.CreateTime
     *
     * @return the value of t_coin_info.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.CreateTime
     *
     * @param createTime the value for t_coin_info.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.UpdateTime
     *
     * @return the value of t_coin_info.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.UpdateTime
     *
     * @param updateTime the value for t_coin_info.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.IsToken
     *
     * @return the value of t_coin_info.IsToken
     *
     * @mbggenerated
     */
    public Boolean getIsToken() {
        return isToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.IsToken
     *
     * @param isToken the value for t_coin_info.IsToken
     *
     * @mbggenerated
     */
    public void setIsToken(Boolean isToken) {
        this.isToken = isToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.Enable
     *
     * @return the value of t_coin_info.Enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.Enable
     *
     * @param enable the value for t_coin_info.Enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.ChainEnable
     *
     * @return the value of t_coin_info.ChainEnable
     *
     * @mbggenerated
     */
    public Boolean getChainEnable() {
        return chainEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.ChainEnable
     *
     * @param chainEnable the value for t_coin_info.ChainEnable
     *
     * @mbggenerated
     */
    public void setChainEnable(Boolean chainEnable) {
        this.chainEnable = chainEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.L2Enable
     *
     * @return the value of t_coin_info.L2Enable
     *
     * @mbggenerated
     */
    public Boolean getL2Enable() {
        return l2Enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.L2Enable
     *
     * @param l2Enable the value for t_coin_info.L2Enable
     *
     * @mbggenerated
     */
    public void setL2Enable(Boolean l2Enable) {
        this.l2Enable = l2Enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.GateWayEnable
     *
     * @return the value of t_coin_info.GateWayEnable
     *
     * @mbggenerated
     */
    public Boolean getGateWayEnable() {
        return gateWayEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.GateWayEnable
     *
     * @param gateWayEnable the value for t_coin_info.GateWayEnable
     *
     * @mbggenerated
     */
    public void setGateWayEnable(Boolean gateWayEnable) {
        this.gateWayEnable = gateWayEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.Decimals
     *
     * @return the value of t_coin_info.Decimals
     *
     * @mbggenerated
     */
    public Integer getDecimals() {
        return decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.Decimals
     *
     * @param decimals the value for t_coin_info.Decimals
     *
     * @mbggenerated
     */
    public void setDecimals(Integer decimals) {
        this.decimals = decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.MaxWithDrawAmount
     *
     * @return the value of t_coin_info.MaxWithDrawAmount
     *
     * @mbggenerated
     */
    public BigInteger getMaxWithDrawAmount() {
        if(maxWithDrawAmount==null || maxWithDrawAmount.length==0)
            return null;
        return new BigInteger(maxWithDrawAmount);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.MaxWithDrawAmount
     *
     * @param maxWithDrawAmount the value for t_coin_info.MaxWithDrawAmount
     *
     * @mbggenerated
     */
    public void setMaxWithDrawAmount(BigInteger maxWithDrawAmount) {
        this.maxWithDrawAmount = maxWithDrawAmount.toByteArray();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.MinWithDrawAmount
     *
     * @return the value of t_coin_info.MinWithDrawAmount
     *
     * @mbggenerated
     */
    public BigInteger getMinWithDrawAmount() {
        if(minWithDrawAmount==null || minWithDrawAmount.length==0)
            return null;
        return new BigInteger(minWithDrawAmount);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.MinWithDrawAmount
     *
     * @param minWithDrawAmount the value for t_coin_info.MinWithDrawAmount
     *
     * @mbggenerated
     */
    public void setMinWithDrawAmount(BigInteger minWithDrawAmount) {
        this.minWithDrawAmount = minWithDrawAmount.toByteArray();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coin_info.MinObtainAmount
     *
     * @return the value of t_coin_info.MinObtainAmount
     *
     * @mbggenerated
     */
    public BigInteger getMinObtainAmount() {
        if(minObtainAmount==null || minObtainAmount.length==0)
            return null;
        return new BigInteger(minObtainAmount);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coin_info.MinObtainAmount
     *
     * @param minObtainAmount the value for t_coin_info.MinObtainAmount
     *
     * @mbggenerated
     */
    public void setMinObtainAmount(BigInteger minObtainAmount) {
        this.minObtainAmount = minObtainAmount.toByteArray();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coin_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coinCode=").append(coinCode);
        sb.append(", chainCode=").append(chainCode);
        sb.append(", contractAddr=").append(contractAddr);
        sb.append(", coinDesc=").append(coinDesc);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isToken=").append(isToken);
        sb.append(", enable=").append(enable);
        sb.append(", chainEnable=").append(chainEnable);
        sb.append(", l2Enable=").append(l2Enable);
        sb.append(", gateWayEnable=").append(gateWayEnable);
        sb.append(", decimals=").append(decimals);
        sb.append(", maxWithDrawAmount=").append(maxWithDrawAmount);
        sb.append(", minWithDrawAmount=").append(minWithDrawAmount);
        sb.append(", minObtainAmount=").append(minObtainAmount);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coin_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoinInfo other = (CoinInfo) that;
        return (this.getCoinCode() == null ? other.getCoinCode() == null : this.getCoinCode().equals(other.getCoinCode()))
                && (this.getChainCode() == null ? other.getChainCode() == null : this.getChainCode().equals(other.getChainCode()))
                && (this.getContractAddr() == null ? other.getContractAddr() == null : this.getContractAddr().equals(other.getContractAddr()))
                && (this.getCoinDesc() == null ? other.getCoinDesc() == null : this.getCoinDesc().equals(other.getCoinDesc()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getIsToken() == null ? other.getIsToken() == null : this.getIsToken().equals(other.getIsToken()))
                && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
                && (this.getChainEnable() == null ? other.getChainEnable() == null : this.getChainEnable().equals(other.getChainEnable()))
                && (this.getL2Enable() == null ? other.getL2Enable() == null : this.getL2Enable().equals(other.getL2Enable()))
                && (this.getGateWayEnable() == null ? other.getGateWayEnable() == null : this.getGateWayEnable().equals(other.getGateWayEnable()))
                && (this.getDecimals() == null ? other.getDecimals() == null : this.getDecimals().equals(other.getDecimals()))
                && (this.getMaxWithDrawAmount() == null ? other.getMaxWithDrawAmount() == null : this.getMaxWithDrawAmount().equals(other.getMaxWithDrawAmount()))
                && (this.getMinWithDrawAmount() == null ? other.getMinWithDrawAmount() == null : this.getMinWithDrawAmount().equals(other.getMinWithDrawAmount()))
                && (this.getMinObtainAmount() == null ? other.getMinObtainAmount() == null : this.getMinObtainAmount().equals(other.getMinObtainAmount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coin_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCoinCode() == null) ? 0 : getCoinCode().hashCode());
        result = prime * result + ((getChainCode() == null) ? 0 : getChainCode().hashCode());
        result = prime * result + ((getContractAddr() == null) ? 0 : getContractAddr().hashCode());
        result = prime * result + ((getCoinDesc() == null) ? 0 : getCoinDesc().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsToken() == null) ? 0 : getIsToken().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getChainEnable() == null) ? 0 : getChainEnable().hashCode());
        result = prime * result + ((getL2Enable() == null) ? 0 : getL2Enable().hashCode());
        result = prime * result + ((getGateWayEnable() == null) ? 0 : getGateWayEnable().hashCode());
        result = prime * result + ((getDecimals() == null) ? 0 : getDecimals().hashCode());
        result = prime * result + ((getMaxWithDrawAmount() == null) ? 0 : getMaxWithDrawAmount().hashCode());
        result = prime * result + ((getMinWithDrawAmount() == null) ? 0 : getMinWithDrawAmount().hashCode());
        result = prime * result + ((getMinObtainAmount() == null) ? 0 : getMinObtainAmount().hashCode());
        return result;
    }
}